(div `(,(class "building_list_item" "closed"))
     (div `(,(class "title"))
          (div `(,(class "icon_container"))
               (svg `(,(width "64") ,(height "64"))
                    (use `(,(href "#building_node_defs") ,(x "32") ,(y "32")))))
          (div `(,(class "title_and_cost"))
               (div `(,(class "title")) "node")
               (div `(,(class "cost"))
                    (div `(,(class "cost_item"))
                         (div `(,(class "cost_amount")) "2")
                         (div `(,(class "cost_currency")) "STA")))))
     (div `(,(class "expand_toggler"))
          (img `(,(class "expand_toggler_img" "open") ,(width "32") ,(height "32"))))
     (div `(,(class "content")) (brify "a traffic node." "you need these and roads for your units to be able to move." nil "it's a traffic node" "you need these and roads to have" "some units that move")))
