(require :asdf)
(asdf:load-system "htmlisp")
;;(asdf:load-system "transclude")

(defvar out
  (concatenate
   'string
   "<!doctype html>"
   (html
    ("html" "head" "title" "meta" "link" "script" "body" "div" "svg" "defs" "g" "foreignObject" "h1" "h2" "h3" "img" "br" "b" "i" "use" "input" "button")
    (attributes
     ("charset" "name" "content" "rel" "href" "type" "src" "onload" "id" "style" "x" "y" "width" "height" "onclick")
     (flet ((class (&rest classes) (format nil "class=\"~{~a~^ ~}\"" classes)))
       (html
        (head
         (meta `(,(charset "UTF-8")))
         (meta `(,(name "author") ,(content "hexa6")))
         (link `(,(rel "icon") ,(href " ")))
         (link `(,(rel "stylesheet") ,(href "src/layout.css")))
         (link `(,(rel "stylesheet") ,(href "themes/default.css")))
         (link `(,(rel "stylesheet") ,(href "src/tabs.css")))
         (script `(,(type "text/javascript") ,(src "src/graphics.js")))
         (script `(,(type "text/javascript") ,(src "src/main.js")))
         (title "kiraton"))
        (body
         `(,(onload "init()"))
         (div
          `(,(id "main"))
          (svg
           `(,(id "c") ,(style "width: 100%; height: 100%"))
           (defs)
           (g `(,(id "camera"))
              (g `(,(id "halos"))
                 (g `(,(id "halos_edges")))
                 (g `(,(id "halos_fills"))))
              (g `(,(id "roads")))
              (g `(,(id "buildings")))
              (g `(,(id "items")))
              (g `(,(id "units"))))
           (g `(,(id "ui"))
              (foreignobject
               `(,(x "70%") ,(y "0") ,(width "30%") ,(height "100%"))
               (div `(,(id "right_sidebar"))
                    (div `(,(id "left_tabs") ,(class "sidebar" "left_tabs"))
                         (flet ((tab (name &optional (active-p nil))
                                  (div (list (id (concatenate 'string name "_tab")) (class "left_tab" (if active-p "active" "inactive")))
                                       (div (list (class "text_vertical_left")) name))))
                           (concatenate 'string
                                        (tab "build" t)
                                        (tab "population")
                                        (tab "units")
                                        (tab "debug"))))
                    (div `(,(id "right_sidebar_content") ,(class "sidebar" "content" "state" "build" "select"))
                         (div `(,(class "build" "content" "page"))
                              (div `(,(class "title"))
                                   (h1 `(,(class "content_title")) "build")
                                   (div `(,(class "content_right")) (div `(,(class "close_button")) "close")))
                              (div `(,(class "build_select" "content" "centered"))
                                   (div `(,(style "text-align: center")) "click to select a building to build from"))
                              (div `(,(class "build" "content"))
                                   (div
                                    (div `(,(class "info_tab" "inner_tab" "closed"))
                                         (div `(,(class "title"))
                                              (h2 "info (partially implemented")
                                              (div `(,(class "expand_toggler")) (img `(,(class "open") ,(width "32") ,(height "32")))))
                                         (div `(,(class "content"))
                                              (div `(,(class "node"))
                                                   "node buildings don't have any information yet!"
                                                   (br)
                                                   "(though they might at some point)")))
                                    (div `(,(class "list_tab" "inner_tab" "closed"))
                                         (div `(,(class "title"))
                                              (h2 "build (not implemented)")
                                              (div `(,(class "expand_toggler")) (img `(,(class "open") ,(width "32") ,(height "32")))))
                                         (div `(,(class "content"))
                                              (div `(,(class "building_list_item" "closed"))
                                                   (div `(,(class "title"))
                                                        (div `(,(class "icon_container")) (svg `(,(width "64") ,(height "64")) (use `(,(href "#building_node_defs") ,(x "32") ,(y "32")))))
                                                        (div (div "node")
                                                             (div (div (div "2") (div "STA"))))
                                                        (div `(,(class "expand_toggler")) (img `(,(class "open") ,(width "32") ,(height "32")))))
                                                   (div `(,(class "content"))
                                                        "a traffic node." (br)
                                                        "you need these and roads for your units to be able to move." (br) (br)
                                                        "it's a traffic node" (br)
                                                        "you need these and roads to have" (br)
                                                        "some units that move")))))))
                         (div `(,(class "population" "content" "page"))
                              (div `(,(class "title"))
                                   (h1 `(,(class "content_title")) "population")
                                   (div `(,(class "content_right")) (div `(,(class "close_button")) "close")))
                              (div `(,(class "overview" "content"))))
                         (div `(,(class "units" "content" "page"))
                              (div `(,(class "title"))
                                   (h1 `(,(class "content_title")) "units")
                                   (div `(,(class "content_right")) (div `(,(class "close_button")) "close")))
                              (div `(,(class "overview" "content"))))
                         (div `(,(class "debug" "content" "page"))
                              (div `(,(class "title"))
                                   (h1 `(,(class "content_title")) "debug")
                                   (div `(,(class "content_right")) (div `(,(class "close_button")) "close")))
                              (div `(,(class "overview" "content"))
                                   (div `(,(class "inner_tab" "open"))
                                        (div `(,(class "title"))
                                             (h2 "change font")
                                             (div `(,(class "expand_toggler")) (img `(,(class "close") ,(width "32") ,(height "32")))))
                                        (div `(,(class "content"))
                                             (labels ((font-button (font-name)
                                                      (button (list (onclick (concatenate 'string "_set_font('" font-name "')")))
                                                              (string-downcase font-name)))
                                                      (font-button-group (&rest names)
                                                        (apply #'concatenate 'string (mapcar #'font-button names))))
                                               (div `(,(style "display: flex; flex-direction: column"))
                                                    "mono"
                                                    (font-button-group "Fira Code" "Ubuntu Mono" "Inconsolata" "Source Code Pro" "IBM Plex Mono")
                                                    (button `(,(onclick "_set_font('monospace')")) "default")
                                                    "sans"
                                                    (font-button-group "Baloo 2" "ABeeZee" "Montserrat" "Roboto" "Fira Sans" "Ubuntu" "IBM Plex Sans")
                                                    (button `(,(onclick "_set_font('sans')")) "default")
                                                    "serif"
                                                    (font-button-group "Vollkorn" "DM Serif Text" "Josefin Slab" "EB Garamond")
                                                    (button `(,(onclick "_set_font('serif')")) "default")))
                                             (div `(,(id "debug_change_font") ,(class "inner_tab" "closed"))
                                                  (div `(,(class "title"))
                                                       (h3 "use specific font")
                                                       (div `(,(class "expand_toggler")) (img `(,(class "open") ,(width "32") ,(height "32")))))
                                                  (div `(,(class "content"))
                                                       (div "choose a font from google fonts." (br) "the font " (b "must") " be capitalised appropriately")
                                                       (input `(,(type "text")))
                                                       (button `(,(onclick "_set_font(this.previousSibling.value)")) "set"))))))))))))))))))))

(with-open-file (ind "index.html"
                     :direction :output
                     :if-exists :supersede
                     :if-does-not-exist :create)
  (format ind "~a~%" out))
